export const VISIBLE_CONTEXT_CARDS = 2;

export const CARD_ASPECT_RATIO = "1 / 1.45";
export const CARD_CORNER_RADIUS = 22;
export const FOCUSED_CARD_CORNER_RADIUS = 30;

export const PROGRESSION_CARD_WIDTH = "min(64vw, 252px)";
export const FOCUSED_CARD_WIDTH = "min(92vw, 430px)";
export const PAST_TABLE_CARD_WIDTH = "min(38vw, 148px)";

export const PROGRESSION_SCENE_HEIGHT = "clamp(550px, 72svh, 640px)";

export const ACTIVE_CARD_OCCLUSION_RELIEF = 8;
export const FUTURE_ZONE_HEIGHT = 90;
export const TABLE_ZONE_TOP = 474;

export const FUTURE_HEADER_OFFSET = 18;
export const FUTURE_FIRST_REVEAL_OFFSET = 28;
export const FUTURE_SECOND_REVEAL_OFFSET = 61;
export const FUTURE_COMPRESSED_OFFSET = 14;
export const FUTURE_READABLE_COUNT = 3;
export const FUTURE_CONTINUATION_Y_INITIAL_OFFSET = 7.5;
export const FUTURE_CONTINUATION_Y_MIN_OFFSET = 0.7;
export const FUTURE_CONTINUATION_Y_OFFSET_DECAY = 0.56;
export const FUTURE_MAX_STACK_DEPTH = 136.5;
export const FUTURE_CONTINUATION_X_INITIAL_OFFSET = 2;
export const FUTURE_CONTINUATION_X_MIN_OFFSET = 0.5;
export const FUTURE_CONTINUATION_X_OFFSET_DECAY = 0.5;
export const FUTURE_CONTINUATION_MAX_X_OFFSET = 10;
export const FUTURE_FIRST_ROTATION_DEGREES = 6.9;
export const FUTURE_SECOND_ROTATION_DEGREES = 14.0;
export const FUTURE_CONTINUATION_ROTATION_INITIAL_OFFSET = 1.1;
export const FUTURE_CONTINUATION_ROTATION_MIN_OFFSET = 0.08;
export const FUTURE_CONTINUATION_ROTATION_OFFSET_DECAY = 0.52;
export const FUTURE_ROTATION_MAX_DEGREES = 16.8;
export const FUTURE_ROTATION_X_DRIFT = 1.35;
export const FUTURE_ROTATION_MAX_X_DRIFT = 3.6;
export const FUTURE_ROTATION_Y_LIFT = 0.25;
export const FUTURE_ROTATION_MAX_Y_LIFT = 0.75;

export const PAST_TABLE_X_OFFSET = 54;
export const PAST_TABLE_THIRD_X_OFFSET = 42;
export const PAST_TABLE_TRACE_INITIAL_X_OFFSET = 16;
export const PAST_TABLE_MIN_X_OFFSET = 5;
export const PAST_TABLE_X_OFFSET_DECAY = 0.55;

export const FUTURE_X_OFFSET = 2.25;

export const CARD_SCALE_STEP = 0.035;
export const PAST_CARD_SCALE_STEP = 0.035;
export const MAX_SCALE_REDUCTION = 0.14;

export const CARD_OPACITY_STEP = 0.08;
export const PAST_CARD_OPACITY_STEP = 0.025;
export const MIN_STACK_OPACITY = 0.58;

export const ROLE_TRANSITION_SETTLE_MS = 360;
